# 欢迎来到美丽的杰基尔！
# 此配置文件用于影响整个网站的设置。 当你第一次
# 设置你的网站，你应该完成所有这些设置并编辑它们，但是之后
# 初始设置您不需要经常回到这个文件。
# --- 必需的选项 --- #

# 网站名称
title: DBLOG

# 你的名字显示在页脚
author: DYUNS域名网-https://www.dyuns.com

# --- 导航栏中的链接列表 --- #

navbar-links:
  About Me: "DBLOG"
  Resources:
    - DYUNS域名网: "https://www.dyuns.com/"
  Author's home: "https://www.dyuns.com"

# --- 标识 --- #
# 显示在导航栏中的图像 - 最适合方形图像
# 如果你不想在导航栏中显示图像，请删除此参数
#avatar: "/assets/img/avatar-icon.png"

# 默认情况下，图像被切割成圆形。 您可以通过设置“round-avatar: false”来禁用此行为
round-avatar: true

# 如果你想在左上角有一个图像标志而不是网站的标题，
# 然后指定以下参数
# title-img: /path/to/image


# --- 页脚社交媒体链接 --- #

# 选择要在页脚中显示的社交网络链接。
# 取消注释您要显示的链接并将您的信息添加到每个链接。
social-network-links:
  email: "support@tablemates.cn"
#  facebook: deanattali
#  github: daattali
#  twitter: daattali
#  patreon: DeanAttali
#  youtube: c/daattali
#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

# 如果要在页脚中显示指向 RSS 的链接，请在此处添加站点说明。
# 如果您不想显示 RSS 链接，请删除以下行。
# rss-description: This website is a virtual proof that I'm awesome

# --- 常规选项 --- #

# 选择要在帖子中显示的社交网络共享链接
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

# 如何在页脚中显示指向您网站的链接
# 如果你不想要页脚中的链接，请删除它
url-pretty: "https://www.dyuns.com"

# 摘录字长 - 将提要页面上每个帖子的摘录截断为指定的字数
excerpt_length: 50

# 是否在提要页面中显示每篇博文的摘录
feed_show_excerpt: true

# 是否在提要页面中每个帖子预览下方显示标签列表
feed_show_tags: true

# 在导航栏中添加搜索按钮
post_search: true

# 与您的网站相关联的关键字，用于 SEO 目的
#keywords: "blog,dblog,dyuns-blog"

# --- 颜色/背景图片 --- #

# 个性化您网站中的颜色。 颜色值可以是任何有效的 CSS 颜色

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# 或者，导航栏、页脚和页面背景可以设置为图像
# 代替颜色

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# 为移动浏览器推荐一种颜色作为浏览器的主题。 这仅受少数移动浏览器支持。
#mobile-theme-col: "#0085A1"

# 对于任何额外的视觉定制，您可以在站点的每个页面中包含额外的 CSS 文件。 在此处列出任何自定义 CSS 文件
#site-css:
#  - "/assets/css/custom-styles.css"

# 如果您有应该包含在每个页面中的常见 JavaScript 文件，请在此处列出它们
#site-js:
#  - "/assets/js/custom-script.js"

# --- 网络分析部分 --- #

# 填写您的 Google Analytics gtag.js ID 以使用 gtag 跟踪您的网站
#gtag: ""

# 填写您的 Google Analytics ID 以使用 Google Analytics 跟踪您的网站
#google_analytics: ""

# 填写您的 Cloudflare Analytics 信标令牌以使用 Cloudflare Analytics 跟踪您的网站
#cloudflare_analytics: ""

# 谷歌标签管理器 ID
#gtm: ""

# Matomo（又名 Piwik）网络统计
# 取消对以下部分的注释以启用 Matomo。 选择退出参数控制
# 是否允许用户选择退出跟踪。
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

＃  - - 注释  - - ＃

# 要使用 Disqus 评论，请注册 https://disqus.com 并填写您的 Disqus 短名称（不是用户 ID）
#disqus: ""

# 要使用 Facebook 评论，请创建一个 Facebook 应用并填写 Facebook 应用 ID
#fb_comment_id: ""

# 使用Utterances 注释：(0) 取消对以下部分的注释，(1) 填写
# “repository”（确保存储库是公开的），（2）在存储库中启用问题，
# (3) 在您的存储库中安装 Utterances 应用程序 https://github.com/apps/utterances
# 请在 https://utteranc.es/ 查看有关以下参数的更多详细信息
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# 要使用 Staticman 注释，请取消注释以下部分。 你可以离开 reCaptcha
如果您不使用 reCaptcha 进行垃圾邮件保护，# 部分已评论。
# 使用Staticman需要高级知识，请咨询
# https://github.com/eduardoboucas/staticman/ 和 https://staticman.net/ 进一步了解
＃ 指示。 对于 staticman 的任何支持，请将问题直接发送给 staticman 和
# 不是 BeautifulJekyll。
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well) 
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# --- 杂项 --- #

# Ruby 日期格式来显示帖子的日期
date_format: "%B %-d, %Y"

# Facebook 应用程序 ID
#fb_app_id: ""

# --- 你不需要触摸这里下面的任何东西（但如果你愿意，你可以）--- #

# 输出选项（有关 Jekyll 站点的更多信息）
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# 默认 YAML 值（有关 Jekyll 站点的更多信息）
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# 从生产站点中排除这些文件
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# 美丽的 Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189


#使用DYUNS中文翻译版必须完整保留版权信息，违者必究！
#--- 版权信息 - 开始 ---
#中文注解及翻译由DYUNS域名网、DYUNS云服务提供。
#DYUNS域名网：https://www.dyuns.com
#邮箱地址：support@tablemates.cn
#---版权信息 - 结束 ---
